//#line 2 "/opt/ros/groovy/share/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the cvt_ros package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __cvt_ros__CHAMELEONSETTINGSCONFIG_H__
#define __cvt_ros__CHAMELEONSETTINGSCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace cvt_ros
{
  class ChameleonSettingsConfigStatics;
  
  class ChameleonSettingsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(ChameleonSettingsConfig &config, const ChameleonSettingsConfig &max, const ChameleonSettingsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const ChameleonSettingsConfig &config1, const ChameleonSettingsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, ChameleonSettingsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const ChameleonSettingsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ChameleonSettingsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const ChameleonSettingsConfig &config) const = 0;
      virtual void getValue(const ChameleonSettingsConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T ChameleonSettingsConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (ChameleonSettingsConfig::* field);

      virtual void clamp(ChameleonSettingsConfig &config, const ChameleonSettingsConfig &max, const ChameleonSettingsConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const ChameleonSettingsConfig &config1, const ChameleonSettingsConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, ChameleonSettingsConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const ChameleonSettingsConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ChameleonSettingsConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const ChameleonSettingsConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const ChameleonSettingsConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, ChameleonSettingsConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); i++)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;
        
        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++) 
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }
      
      virtual void updateParams(boost::any &cfg, ChameleonSettingsConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++) 
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<ChameleonSettingsConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(ChameleonSettingsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = params.begin(); i != params.end(); i++)
      {
        boost::any val;
        (*i)->getValue(config, val);

        if("shutter_mode"==(*i)->name){shutter_mode = boost::any_cast<int>(val);}
        if("exposure_mode"==(*i)->name){exposure_mode = boost::any_cast<int>(val);}
        if("gain_mode"==(*i)->name){gain_mode = boost::any_cast<int>(val);}
        if("white_balance_mode"==(*i)->name){white_balance_mode = boost::any_cast<int>(val);}
        if("shutter_value"==(*i)->name){shutter_value = boost::any_cast<double>(val);}
        if("exposure_value"==(*i)->name){exposure_value = boost::any_cast<double>(val);}
        if("gain_value"==(*i)->name){gain_value = boost::any_cast<double>(val);}
        if("white_balance_ub_value"==(*i)->name){white_balance_ub_value = boost::any_cast<int>(val);}
        if("white_balance_vr_value"==(*i)->name){white_balance_vr_value = boost::any_cast<int>(val);}
        if("useAutoShutter"==(*i)->name){useAutoShutter = boost::any_cast<bool>(val);}
        if("trigger"==(*i)->name){trigger = boost::any_cast<bool>(val);}
      }
    }

    int shutter_mode;
int exposure_mode;
int gain_mode;
int white_balance_mode;
double shutter_value;
double exposure_value;
double gain_value;
int white_balance_ub_value;
int white_balance_vr_value;
bool useAutoShutter;
bool trigger;

    bool state;
    std::string name;

    
}groups;



//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int shutter_mode;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int exposure_mode;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int gain_mode;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int white_balance_mode;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double shutter_value;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double exposure_value;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double gain_value;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int white_balance_ub_value;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int white_balance_vr_value;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool useAutoShutter;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool trigger;
//#line 255 "/opt/ros/groovy/share/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("ChameleonSettingsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const ChameleonSettingsConfig &__max__ = __getMax__();
      const ChameleonSettingsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const ChameleonSettingsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const ChameleonSettingsConfig &__getDefault__();
    static const ChameleonSettingsConfig &__getMax__();
    static const ChameleonSettingsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const ChameleonSettingsConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void ChameleonSettingsConfig::ParamDescription<std::string>::clamp(ChameleonSettingsConfig &config, const ChameleonSettingsConfig &max, const ChameleonSettingsConfig &min) const
  {
    return;
  }

  class ChameleonSettingsConfigStatics
  {
    friend class ChameleonSettingsConfig;
    
    ChameleonSettingsConfigStatics()
    {
ChameleonSettingsConfig::GroupDescription<ChameleonSettingsConfig::DEFAULT, ChameleonSettingsConfig> Default("Default", "", 0, 0, true, &ChameleonSettingsConfig::groups);
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.shutter_mode = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.shutter_mode = 2;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.shutter_mode = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ChameleonSettingsConfig::AbstractParamDescriptionConstPtr(new ChameleonSettingsConfig::ParamDescription<int>("shutter_mode", "int", 0, "Shutter Control Mode", "{'enum_description': 'An enum to set feature modes', 'enum': [{'srcline': 9, 'description': 'Automatic mode', 'srcfile': '/home/kloses/Develop/catkin_ws/src/cvt_ros/cvt_ros/cfg/ChameleonSettings.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'AUTO'}, {'srcline': 10, 'description': 'Manual mode', 'srcfile': '/home/kloses/Develop/catkin_ws/src/cvt_ros/cvt_ros/cfg/ChameleonSettings.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'MANUAL'}, {'srcline': 11, 'description': 'One Push Automatic mode', 'srcfile': '/home/kloses/Develop/catkin_ws/src/cvt_ros/cvt_ros/cfg/ChameleonSettings.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'ONE_PUSH_AUTO'}]}", &ChameleonSettingsConfig::shutter_mode)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ChameleonSettingsConfig::AbstractParamDescriptionConstPtr(new ChameleonSettingsConfig::ParamDescription<int>("shutter_mode", "int", 0, "Shutter Control Mode", "{'enum_description': 'An enum to set feature modes', 'enum': [{'srcline': 9, 'description': 'Automatic mode', 'srcfile': '/home/kloses/Develop/catkin_ws/src/cvt_ros/cvt_ros/cfg/ChameleonSettings.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'AUTO'}, {'srcline': 10, 'description': 'Manual mode', 'srcfile': '/home/kloses/Develop/catkin_ws/src/cvt_ros/cvt_ros/cfg/ChameleonSettings.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'MANUAL'}, {'srcline': 11, 'description': 'One Push Automatic mode', 'srcfile': '/home/kloses/Develop/catkin_ws/src/cvt_ros/cvt_ros/cfg/ChameleonSettings.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'ONE_PUSH_AUTO'}]}", &ChameleonSettingsConfig::shutter_mode)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.exposure_mode = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.exposure_mode = 2;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.exposure_mode = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ChameleonSettingsConfig::AbstractParamDescriptionConstPtr(new ChameleonSettingsConfig::ParamDescription<int>("exposure_mode", "int", 0, "Exposure Control Mode", "{'enum_description': 'An enum to set feature modes', 'enum': [{'srcline': 9, 'description': 'Automatic mode', 'srcfile': '/home/kloses/Develop/catkin_ws/src/cvt_ros/cvt_ros/cfg/ChameleonSettings.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'AUTO'}, {'srcline': 10, 'description': 'Manual mode', 'srcfile': '/home/kloses/Develop/catkin_ws/src/cvt_ros/cvt_ros/cfg/ChameleonSettings.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'MANUAL'}, {'srcline': 11, 'description': 'One Push Automatic mode', 'srcfile': '/home/kloses/Develop/catkin_ws/src/cvt_ros/cvt_ros/cfg/ChameleonSettings.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'ONE_PUSH_AUTO'}]}", &ChameleonSettingsConfig::exposure_mode)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ChameleonSettingsConfig::AbstractParamDescriptionConstPtr(new ChameleonSettingsConfig::ParamDescription<int>("exposure_mode", "int", 0, "Exposure Control Mode", "{'enum_description': 'An enum to set feature modes', 'enum': [{'srcline': 9, 'description': 'Automatic mode', 'srcfile': '/home/kloses/Develop/catkin_ws/src/cvt_ros/cvt_ros/cfg/ChameleonSettings.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'AUTO'}, {'srcline': 10, 'description': 'Manual mode', 'srcfile': '/home/kloses/Develop/catkin_ws/src/cvt_ros/cvt_ros/cfg/ChameleonSettings.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'MANUAL'}, {'srcline': 11, 'description': 'One Push Automatic mode', 'srcfile': '/home/kloses/Develop/catkin_ws/src/cvt_ros/cvt_ros/cfg/ChameleonSettings.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'ONE_PUSH_AUTO'}]}", &ChameleonSettingsConfig::exposure_mode)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.gain_mode = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.gain_mode = 2;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.gain_mode = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ChameleonSettingsConfig::AbstractParamDescriptionConstPtr(new ChameleonSettingsConfig::ParamDescription<int>("gain_mode", "int", 0, "Gain Control Mode", "{'enum_description': 'An enum to set feature modes', 'enum': [{'srcline': 9, 'description': 'Automatic mode', 'srcfile': '/home/kloses/Develop/catkin_ws/src/cvt_ros/cvt_ros/cfg/ChameleonSettings.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'AUTO'}, {'srcline': 10, 'description': 'Manual mode', 'srcfile': '/home/kloses/Develop/catkin_ws/src/cvt_ros/cvt_ros/cfg/ChameleonSettings.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'MANUAL'}, {'srcline': 11, 'description': 'One Push Automatic mode', 'srcfile': '/home/kloses/Develop/catkin_ws/src/cvt_ros/cvt_ros/cfg/ChameleonSettings.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'ONE_PUSH_AUTO'}]}", &ChameleonSettingsConfig::gain_mode)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ChameleonSettingsConfig::AbstractParamDescriptionConstPtr(new ChameleonSettingsConfig::ParamDescription<int>("gain_mode", "int", 0, "Gain Control Mode", "{'enum_description': 'An enum to set feature modes', 'enum': [{'srcline': 9, 'description': 'Automatic mode', 'srcfile': '/home/kloses/Develop/catkin_ws/src/cvt_ros/cvt_ros/cfg/ChameleonSettings.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'AUTO'}, {'srcline': 10, 'description': 'Manual mode', 'srcfile': '/home/kloses/Develop/catkin_ws/src/cvt_ros/cvt_ros/cfg/ChameleonSettings.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'MANUAL'}, {'srcline': 11, 'description': 'One Push Automatic mode', 'srcfile': '/home/kloses/Develop/catkin_ws/src/cvt_ros/cvt_ros/cfg/ChameleonSettings.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'ONE_PUSH_AUTO'}]}", &ChameleonSettingsConfig::gain_mode)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.white_balance_mode = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.white_balance_mode = 2;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.white_balance_mode = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ChameleonSettingsConfig::AbstractParamDescriptionConstPtr(new ChameleonSettingsConfig::ParamDescription<int>("white_balance_mode", "int", 0, "White-Bal. Mode", "{'enum_description': 'An enum to set feature modes', 'enum': [{'srcline': 9, 'description': 'Automatic mode', 'srcfile': '/home/kloses/Develop/catkin_ws/src/cvt_ros/cvt_ros/cfg/ChameleonSettings.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'AUTO'}, {'srcline': 10, 'description': 'Manual mode', 'srcfile': '/home/kloses/Develop/catkin_ws/src/cvt_ros/cvt_ros/cfg/ChameleonSettings.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'MANUAL'}, {'srcline': 11, 'description': 'One Push Automatic mode', 'srcfile': '/home/kloses/Develop/catkin_ws/src/cvt_ros/cvt_ros/cfg/ChameleonSettings.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'ONE_PUSH_AUTO'}]}", &ChameleonSettingsConfig::white_balance_mode)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ChameleonSettingsConfig::AbstractParamDescriptionConstPtr(new ChameleonSettingsConfig::ParamDescription<int>("white_balance_mode", "int", 0, "White-Bal. Mode", "{'enum_description': 'An enum to set feature modes', 'enum': [{'srcline': 9, 'description': 'Automatic mode', 'srcfile': '/home/kloses/Develop/catkin_ws/src/cvt_ros/cvt_ros/cfg/ChameleonSettings.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'AUTO'}, {'srcline': 10, 'description': 'Manual mode', 'srcfile': '/home/kloses/Develop/catkin_ws/src/cvt_ros/cvt_ros/cfg/ChameleonSettings.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'MANUAL'}, {'srcline': 11, 'description': 'One Push Automatic mode', 'srcfile': '/home/kloses/Develop/catkin_ws/src/cvt_ros/cvt_ros/cfg/ChameleonSettings.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'ONE_PUSH_AUTO'}]}", &ChameleonSettingsConfig::white_balance_mode)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.shutter_value = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.shutter_value = 200.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.shutter_value = 5.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ChameleonSettingsConfig::AbstractParamDescriptionConstPtr(new ChameleonSettingsConfig::ParamDescription<double>("shutter_value", "double", 0, "Shutter Time (ms)", "", &ChameleonSettingsConfig::shutter_value)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ChameleonSettingsConfig::AbstractParamDescriptionConstPtr(new ChameleonSettingsConfig::ParamDescription<double>("shutter_value", "double", 0, "Shutter Time (ms)", "", &ChameleonSettingsConfig::shutter_value)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.exposure_value = -2.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.exposure_value = 2.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.exposure_value = 0.8;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ChameleonSettingsConfig::AbstractParamDescriptionConstPtr(new ChameleonSettingsConfig::ParamDescription<double>("exposure_value", "double", 0, "Exposure Value (IL)", "", &ChameleonSettingsConfig::exposure_value)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ChameleonSettingsConfig::AbstractParamDescriptionConstPtr(new ChameleonSettingsConfig::ParamDescription<double>("exposure_value", "double", 0, "Exposure Value (IL)", "", &ChameleonSettingsConfig::exposure_value)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.gain_value = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.gain_value = 20.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.gain_value = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ChameleonSettingsConfig::AbstractParamDescriptionConstPtr(new ChameleonSettingsConfig::ParamDescription<double>("gain_value", "double", 0, "Gain Value (%)", "", &ChameleonSettingsConfig::gain_value)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ChameleonSettingsConfig::AbstractParamDescriptionConstPtr(new ChameleonSettingsConfig::ParamDescription<double>("gain_value", "double", 0, "Gain Value (%)", "", &ChameleonSettingsConfig::gain_value)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.white_balance_ub_value = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.white_balance_ub_value = 1024;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.white_balance_ub_value = 160;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ChameleonSettingsConfig::AbstractParamDescriptionConstPtr(new ChameleonSettingsConfig::ParamDescription<int>("white_balance_ub_value", "int", 0, "White Balance Value (U-B)", "", &ChameleonSettingsConfig::white_balance_ub_value)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ChameleonSettingsConfig::AbstractParamDescriptionConstPtr(new ChameleonSettingsConfig::ParamDescription<int>("white_balance_ub_value", "int", 0, "White Balance Value (U-B)", "", &ChameleonSettingsConfig::white_balance_ub_value)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.white_balance_vr_value = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.white_balance_vr_value = 1024;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.white_balance_vr_value = 160;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ChameleonSettingsConfig::AbstractParamDescriptionConstPtr(new ChameleonSettingsConfig::ParamDescription<int>("white_balance_vr_value", "int", 0, "White Balance Value (V-R)", "", &ChameleonSettingsConfig::white_balance_vr_value)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ChameleonSettingsConfig::AbstractParamDescriptionConstPtr(new ChameleonSettingsConfig::ParamDescription<int>("white_balance_vr_value", "int", 0, "White Balance Value (V-R)", "", &ChameleonSettingsConfig::white_balance_vr_value)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.useAutoShutter = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.useAutoShutter = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.useAutoShutter = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ChameleonSettingsConfig::AbstractParamDescriptionConstPtr(new ChameleonSettingsConfig::ParamDescription<bool>("useAutoShutter", "bool", 0, "Automatic Shutter Regulation", "", &ChameleonSettingsConfig::useAutoShutter)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ChameleonSettingsConfig::AbstractParamDescriptionConstPtr(new ChameleonSettingsConfig::ParamDescription<bool>("useAutoShutter", "bool", 0, "Automatic Shutter Regulation", "", &ChameleonSettingsConfig::useAutoShutter)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.trigger = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.trigger = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.trigger = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ChameleonSettingsConfig::AbstractParamDescriptionConstPtr(new ChameleonSettingsConfig::ParamDescription<bool>("trigger", "bool", 0, "Trigger a frame manually", "", &ChameleonSettingsConfig::trigger)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ChameleonSettingsConfig::AbstractParamDescriptionConstPtr(new ChameleonSettingsConfig::ParamDescription<bool>("trigger", "bool", 0, "Trigger a frame manually", "", &ChameleonSettingsConfig::trigger)));
//#line 233 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 233 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(ChameleonSettingsConfig::AbstractGroupDescriptionConstPtr(new ChameleonSettingsConfig::GroupDescription<ChameleonSettingsConfig::DEFAULT, ChameleonSettingsConfig>(Default)));
//#line 390 "/opt/ros/groovy/share/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<ChameleonSettingsConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<ChameleonSettingsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<ChameleonSettingsConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    ChameleonSettingsConfig __max__;
    ChameleonSettingsConfig __min__;
    ChameleonSettingsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const ChameleonSettingsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static ChameleonSettingsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &ChameleonSettingsConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const ChameleonSettingsConfig &ChameleonSettingsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const ChameleonSettingsConfig &ChameleonSettingsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const ChameleonSettingsConfig &ChameleonSettingsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<ChameleonSettingsConfig::AbstractParamDescriptionConstPtr> &ChameleonSettingsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<ChameleonSettingsConfig::AbstractGroupDescriptionConstPtr> &ChameleonSettingsConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const ChameleonSettingsConfigStatics *ChameleonSettingsConfig::__get_statics__()
  {
    const static ChameleonSettingsConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = ChameleonSettingsConfigStatics::get_instance();
    
    return statics;
  }

//#line 9 "/home/kloses/Develop/catkin_ws/src/cvt_ros/cvt_ros/cfg/ChameleonSettings.cfg"
      const int ChameleonSettings_AUTO = 0;
//#line 10 "/home/kloses/Develop/catkin_ws/src/cvt_ros/cvt_ros/cfg/ChameleonSettings.cfg"
      const int ChameleonSettings_MANUAL = 1;
//#line 11 "/home/kloses/Develop/catkin_ws/src/cvt_ros/cvt_ros/cfg/ChameleonSettings.cfg"
      const int ChameleonSettings_ONE_PUSH_AUTO = 2;
}

#endif // __CHAMELEONSETTINGSRECONFIGURATOR_H__
